#!/bin/bash

if [[ $1 == "launcher" ]]; then
    rofi -combi-modi run,drun -show combi -modi combi,ssh -lines 10 -font "Cantarell 11" -hide-scrollbar
elif [[ $1 == "windows" ]]; then
    rofi -show window -lines 10 -font "Cantarell 11" -hide-scrollbar
fi
