set nocompatible              " be iMproved, required
filetype off                  " required
filetype plugin on
filetype plugin indent on

" --Encoding--
set encoding=utf-8
set termencoding=utf-8

" --Lets--
let g:session_autoload = 'no'
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
let g:ycm_python_binary_path = '/usr/bin/python3'
let g:pymode_rope = 0

" --Mapping--
map <C-t> :NERDTreeToggle<CR>
map <C-a> :bnext<CR>
map <C-d> :bdelete<CR>

" --Tab key--
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

" --Navigation--
set cursorline
set number

" --Color scheme--
syntax enable
set background=dark

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'


Plugin 'tpope/vim-fugitive'
Plugin 'git://git.wincent.com/command-t.git'
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
Plugin 'scrooloose/nerdtree'
Plugin 'valloric/youcompleteme'
Plugin 'easymotion/vim-easymotion'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'flazz/vim-colorschemes'
Plugin 'matze/vim-move'
Plugin 'raimondi/delimitmate'
Plugin 'mattn/emmet-vim'
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-surround'
Plugin 'sirver/ultisnips'
Plugin 'Shougo/neosnippet'
Plugin 'Shougo/neosnippet-snippets'
Plugin 'honza/vim-snippets'
Plugin 'xolox/vim-session'
Plugin 'xolox/vim-misc'
Plugin 'SyntaxAttr.vim'
Plugin 'dyng/ctrlsf.vim'
Plugin 'rking/ag.vim'
Plugin 'godlygeek/tabular'

" --Clang--
Plugin 'Rip-Rip/clang_complete'

" --Python--
Plugin 'klen/python-mode'
Plugin 'mitsuhiko/vim-python-combined'

" --JavaScript--
Plugin 'pangloss/vim-javascript'

" --HTML5--
Plugin 'othree/html5.vim'

" --Themes--
Plugin 'damage220/solas.vim'

call vundle#end()
