set nocompatible              " be iMproved, required
filetype off                  " required
filetype plugin on
filetype plugin indent on

" --Encoding--
set encoding=utf-8
set termencoding=utf-8

" --Airline--
let g:session_autoload = 'no'
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

" --YouCompleteMe--
let g:ycm_global_ycm_extra_conf = '~/.config/nvim/ycm_extra_conf.py'
let g:ycm_python_binary_path = '/usr/bin/python3'
let g:ycm_confirm_extra_conf = 1
let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']

" --UltiSnips--
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"

" --Python-mode--
let g:pymode_rope = 0
let g:pymode_python = 'python3'

" --Mapping--
map <C-t> :NERDTreeToggle<CR>
map <C-a> :bnext<CR>
map <C-d> :bdelete<CR>

" --Tab--
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

" --Navigation--
set cursorline
set number

" --Color scheme--
syntax enable
set background=dark

" --Plugins--

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'tpope/vim-fugitive'
Plugin 'git://git.wincent.com/command-t.git'
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
Plugin 'scrooloose/nerdtree'
Plugin 'valloric/youcompleteme'
Plugin 'easymotion/vim-easymotion'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'rafi/awesome-vim-colorschemes'
Plugin 'chriskempson/vim-tomorrow-theme'
Plugin 'matze/vim-move'
Plugin 'raimondi/delimitmate'
Plugin 'mattn/emmet-vim'
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-surround'
Plugin 'sirver/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'xolox/vim-session'
Plugin 'xolox/vim-misc'
Plugin 'SyntaxAttr.vim'
Plugin 'dyng/ctrlsf.vim'
Plugin 'rking/ag.vim'

" --C/C++--
Plugin 'Rip-Rip/clang_complete'
Plugin 'octol/vim-cpp-enhanced-highlight'

" --Python--
Plugin 'klen/python-mode'
Plugin 'mitsuhiko/vim-python-combined'

" --JavaScript--
Plugin 'pangloss/vim-javascript'

" --HTML5--
Plugin 'othree/html5.vim'

call vundle#end()
