#!/bin/bash

BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')

URGENT_VALUE=15

if [[ "${BATTERY_STATE}" = "Charging" ]]; then
  echo " ${BATTERY_POWER}%"
  echo " ${BATTERY_POWER}%"
  echo ""
elif [[ "${BATTERY_STATE}" = "Full" ]]; then
  echo " ${BATTERY_POWER}%"
  echo " ${BATTERY_POWER}%"
  echo ""
elif [[ "${BATTERY_POWER}" -eq "75" || "${BATTERY_POWER}" -gt "50" ]]; then
  echo " ${BATTERY_POWER}%"
  echo " ${BATTERY_POWER}%"
elif [[ "${BATTERY_POWER}" -eq "50" ]]; then
  echo " ${BATTERY_POWER}%"
  echo " ${BATTERY_POWER}%"
elif [[ "$BATTERY_POWER" -lt "50" ]]; then
  echo " ${BATTERY_POWER}%"
  echo " ${BATTERY_POWER}%"
fi

if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
  echo "#F0544C"
fi
